version: '3.7'

services:
  parsing_miningpoolstats:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && python -s  start_pars.py"
    working_dir: /usr/workspace
    environment:
      - CI_TOKEN=${CI_TOKEN}

