name: Start parsing

#on: workflow_dispatch

on:
  schedule:
    - cron: '05 * * * *'


jobs:
  Go-pars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run-parsing

        run: sudo docker-compose up


