name: Start parsing

#on: workflow_dispatch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'


jobs:
  Go-pars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run-parsing
        run: sudo docker-compose up


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ 'sapfire65/stat_parser' }}
          retain_days: 0
          keep_minimum_runs: 5





