name: Start parsing

on: workflow_dispatch

jobs:
  Go-pars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run-parsing

        run: sudo docker-compose up


